on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: CMake configure
        shell: bash
        run: cmake --preset ninja-multi -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install

      - name: CMake build
        run: cmake --build --preset debug --target install

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install ninja-build

      - name: CMake configure
        shell: bash
        run: cmake --preset ninja-multi -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install

      - name: CMake build
        run: cmake --build --preset debug --target install
